-- Dimensões
CREATE TABLE DIM_CALENDARIO (
    ID_CALENDARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    DATA DATE,
    MES INTEGER,
    ANO INTEGER
);

CREATE TABLE DIM_PDV (
    ID_PDV INTEGER PRIMARY KEY,
    NOME_PONTO_VENDA TEXT,
    PERFIL_PONTO_VENDA TEXT
);

CREATE TABLE DIM_LINHA_PRODUTO (
    ID_LINHA_PRODUTO INTEGER PRIMARY KEY,
    NOME_LINHA_PRODUTO TEXT,
    MARCA_LINHA_PRODUTO TEXT
);

-- Fatos
CREATE TABLE FT_DISPONIBILIDADE (
    ID_CALENDARIO INTEGER,
    ID_PDV INTEGER,
    ID_LINHA_PRODUTO INTEGER,
    PRESENCA_COUNT INTEGER,
    FOREIGN KEY (ID_CALENDARIO) REFERENCES DIM_CALENDARIO(ID_CALENDARIO),
    FOREIGN KEY (ID_PDV) REFERENCES DIM_PDV(ID_PDV),
    FOREIGN KEY (ID_LINHA_PRODUTO) REFERENCES DIM_LINHA_PRODUTO(ID_LINHA_PRODUTO)
);

CREATE TABLE FT_DISPONIBILIDADE_AGREGADA (
    ID_CALENDARIO INTEGER,
    ID_PDV INTEGER,
    PRESENCA_TOTAL INTEGER,
    FOREIGN KEY (ID_CALENDARIO) REFERENCES DIM_CALENDARIO(ID_CALENDARIO),
    FOREIGN KEY (ID_PDV) REFERENCES DIM_PDV(ID_PDV)
);

CREATE TABLE FT_PONTO_EXTRA (
    ID_CALENDARIO INTEGER,
    ID_PDV INTEGER,
    ID_LINHA_PRODUTO INTEGER,
    PONTO_EXTRA_SUM INTEGER,
    FOREIGN KEY (ID_CALENDARIO) REFERENCES DIM_CALENDARIO(ID_CALENDARIO),
    FOREIGN KEY (ID_PDV) REFERENCES DIM_PDV(ID_PDV),
    FOREIGN KEY (ID_LINHA_PRODUTO) REFERENCES DIM_LINHA_PRODUTO(ID_LINHA_PRODUTO)
);

CREATE TABLE FT_PONTO_EXTRA_AGREGADA (
    ID_CALENDARIO INTEGER,
    ID_PDV INTEGER,
    PONTO_EXTRA_TOTAL INTEGER,
    FOREIGN KEY (ID_CALENDARIO) REFERENCES DIM_CALENDARIO(ID_CALENDARIO),
    FOREIGN KEY (ID_PDV) REFERENCES DIM_PDV(ID_PDV)
);