-- Questão 4:

SELECT
    T1.NOME_PDV,
    COUNT(*) AS QUANTIDADE_VISITAS
FROM PONTO_VENDA_UNIDADE AS T1
INNER JOIN VISITAS_PONTO_VENDA AS T2
ON T1.ID_PDV = T2.FK_PDV
WHERE
    (T1.NOME_PDV = "INVOLVES"
    AND
    T2.FL_VISITADO = 1)
GROUP BY NOME_PDV;